export interface IQuotation {
    SeqId: number;
    QuotationNo: string;
    RevisionNo: number;
    LifeAss1Name: string;
    LifeAss1Dob: string;
    LifeAss1Age: number;
    LifeAss1Gender: string;
    LifeAss1Nic: string;
    LifeAss2Name: string;
    LifeAss2Dob: string;
    LifeAss2Age: number;
    LifeAss2Gender: string;
    LifeAss2Nic: string;
    LoanAmount: number;
    Term: number;
    FixedInterest: number;
    CompanyBufferId: number;
    CurrentAwplr: number;
    AdditionalToAwplr: number;
    TermOfFixederest: number;
    Discount: number;
    Premium: number;
    LoanTypeId: number;
    BranchCode: string;
    UserId: string;
    Status: string;
    RegisterDate: string;
}